### PR TITLE
Complete DB lesson2

### PR DESCRIPTION
**Pull request by Merhawi-gebreslasie**

### CODE REVIEW

**Comment by mani-zaeim** [comment]
please close this pull request and re-send, so I can see the most updated one :) thanks

**Comment by Merhawi-gebreslasie** [comment]
🆗👍.

tor. 10. feb. 2022 17.07 skrev Mani Zaeim ***@***.***>:

**Comment by Merhawi-gebreslasie** [comment]
Hi Mani, I closed the pull request and res_send it again ,but it does not look
good,is there anything that  I can do to fix it?

tor. 10. feb. 2022 17.16 skrev Merhawi Gebreslassie ***@***.***>:

**Comment by mani-zaeim** [comment]
make a backup of the code, remove the branch, create a branch, add the files and recommit please. thanks

**Comment by Merhawi-gebreslasie** [comment]
Thanks I have implemented it:)

fre. 11. feb. 2022 13.16 skrev Mani Zaeim ***@***.***>:

**Pull request closed without merging**
